### ISSUE TITLE
腾讯云cos能否增加一个快速切换存储目录的命令？

### ISSUE THREAD

**Issue by purequant** [icexmoon/markdown-img#2]
刚刚试用了一下，程序非常实用。不过，一般而言， 我喜欢一篇markdown文档的图片专门存储在一个目录下，这样方便管理。但是目前程序更换令牌信息，必须所有从头输入非常麻烦（当然可以直接去更改main.config文件），不过我还是想能否直接提供个专门修改存储目录的命令，谢谢。

**Comment by icexmoon** [comment]
你是说COS上存储桶的目录？

**Comment by purequant** [comment]
是的

icexmoon ***@***.***> 于2021年5月25日周二 下午3:29写道：

**Comment by icexmoon** [comment]
那行，我有空添加一下，弄个组合命令吧，以方便以后添加的其它图床个别配置的修改

**Comment by purequant** [comment]
> 那行，我有空添加一下，弄个组合命令吧，以方便以后添加的其它图床个别配置的修改

嗯，还有一个就是能否增加支持这个目录路径存在空格的情况，因为中英文混输的时候，我一般习惯用空格格开。

**Comment by icexmoon** [comment]
> > 那行，我有空添加一下，弄个组合命令吧，以方便以后添加的其它图床个别配置的修改
> 
> 嗯，还有一个就是能否增加支持这个目录路径存在空格的情况，因为中英文混输的时候，我一般习惯用空格格开。

目前有空格会出错？是两头有空格还是中间有空格？

**Comment by purequant** [comment]
> > > 那行，我有空添加一下，弄个组合命令吧，以方便以后添加的其它图床个别配置的修改
> > 
> > 
> > 嗯，还有一个就是能否增加支持这个目录路径存在空格的情况，因为中英文混输的时候，我一般习惯用空格格开。
> 
> 目前有空格会出错？是两头有空格还是中间有空格？

是比如“我 love 你”这个目录，在main.config直接改成这个目录，然后无法正常上传图片。

**Comment by icexmoon** [comment]
> > > > 那行，我有空添加一下，弄个组合命令吧，以方便以后添加的其它图床个别配置的修改
> > > 
> > > 
> > > 嗯，还有一个就是能否增加支持这个目录路径存在空格的情况，因为中英文混输的时候，我一般习惯用空格格开。
> > 
> > 
> > 目前有空格会出错？是两头有空格还是中间有空格？
> 
> 是比如“我 love 你”这个目录，在main.config直接改成这个目录，然后无法正常上传图片。

好的，我会排查和处理的

**Comment by icexmoon** [comment]
已处理
