### ISSUE TITLE
error.log

### ISSUE THREAD

**Issue by scylamb** [icexmoon/markdown-img#3]
{'success': False, 'code': 'invalid_size', 'message': 'Unavailable image format', 'RequestId': '03D1829D-7953-4A00-821E-637CC70FE86F'}
![image](https://user-images.githubusercontent.com/24493892/120581696-cfaa9e00-c45d-11eb-98a5-eb5ee8382527.png)

**Comment by icexmoon** [comment]
从提示信息上看似乎是你的图片格式smms不支持
可以确认一下图片格式是不是主流的jpeg,jpg,png等
或者就是图片过大，smms图床好像最多支持5m大小
或者你可以换个图床服务试试看

**Comment by icexmoon** [comment]
我目前用的腾讯云oss，一年50G免费空间，使用费用相当低，个人站用的话可以忽略不计，当然免费期到期后续费以及如果不续费迁移图片是个大问题，且走且看吧，目前看就算续费资费也可以接受。
关于如何购买使用可以看我这篇：https://blog.icexmoon.xyz/archives/151.html
免费图床好像目前也就smms还行了，就是国内访问偏慢，如果有好的能接入的免费图床欢迎反馈。
