### ISSUE TITLE
目录有空格的情况还对生成的Markdown链接进一步处理一下

### ISSUE THREAD

**Issue by purequant** [icexmoon/markdown-img#4]
请看下例：
![image](https://user-images.githubusercontent.com/26440503/120935134-de31d780-c733-11eb-8928-de26ebf73638.png)

**Comment by icexmoon** [comment]
![image](https://user-images.githubusercontent.com/13990857/120958433-4f9c7500-c78a-11eb-9d7f-0e822eafafdb.png)
我这边并没有复现问题，无论是vscode下的插件还是Typora均显示正常

**Comment by icexmoon** [comment]
虽然没有复现问题，但考虑到可能有人会需要使用URL ENCODE处理图片url这个功能，我已经更新上去了，开启方式文档中有说明，你可以尝试使用这个功能，不知道是否能解决你的问题，如果依然不行的话可以继续反馈，并附上你的markdown文档。

**Comment by purequant** [comment]
您好，更新后已经解决了这个问题。不过能否做到只对空格这样的特殊字符进行编码呢？因为对所有字符都进行编码，会使得阅读Markdown源文件时，分辨图片信息出现困难。

**Comment by icexmoon** [comment]
> 您好，更新后已经解决了这个问题。不过能否做到只对空格这样的特殊字符进行编码呢？因为对所有字符都进行编码，会使得阅读Markdown源文件时，分辨图片信息出现困难。

已经可以使用多种url encode模式，其中`pymdimg -u only_space`是设置为仅对空格进行处理

**Comment by purequant** [comment]
> > 您好，更新后已经解决了这个问题。不过能否做到只对空格这样的特殊字符进行编码呢？因为对所有字符都进行编码，会使得阅读Markdown源文件时，分辨图片信息出现困难。
> 
> 已经可以使用多种url encode模式，其中`pymdimg -u only_space`是设置为仅对空格进行处理

好的非常感谢，已经很好地解决了这个问题
