### ISSUE TITLE
在html中使用B站的外链的方法

### ISSUE THREAD

**Issue by xlzy520** [icexmoon/markdown-img#5]
https://github.com/xlzy520/blog-xlzy/blob/master/docs/01.%E5%89%8D%E7%AB%AF/55.%E6%9D%82%E6%96%87/13.%E9%98%B2%E7%9B%97%E9%93%BE%E9%82%A3%E4%BA%9B%E4%BA%8B%E4%B9%8Breferer.md

**Comment by icexmoon** [comment]
额,这我知道,但是好像没必要,免费的图床也有很多其他的可以选择

**Comment by xlzy520** [comment]
是的，我用B站的主要是速度快，能随意定制图片大小和质量
